// <auto-generated />
using GameShelf.Data;
using GameShelf.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GameShelf.Migrations
{
    [DbContext(typeof(GameShelfContext))]
    [Migration("20180203021332_RoleToEnumRemovedFromPK")]
    partial class RoleToEnumRemovedFromPK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameShelf.Models.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PublicationYear");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameShelf.Models.GamePersonRelationship", b =>
                {
                    b.Property<int>("GameID");

                    b.Property<int>("PersonID");

                    b.Property<int>("Role");

                    b.HasKey("GameID", "PersonID");

                    b.HasIndex("PersonID");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("GameShelf.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("GameShelf.Models.GamePersonRelationship", b =>
                {
                    b.HasOne("GameShelf.Models.Game", "Game")
                        .WithMany("GamePersonRelationships")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameShelf.Models.Person", "Person")
                        .WithMany("RelatedGames")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
